import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";

import localFont from "next/font/local";

const iranSans = localFont({
  src: "/fonts/Vazir-Bold.ttf",
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={iranSans.variable}>
      <body className="font-iran-sans">
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
