// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import HeaderClient from "@/component/HeaderClient"; // Client Component
import localFont from "next/font/local";
import { AuthProvider } from "@/context/AuthContext";
import ConditionalLayout from "@/component/ConditionalHeader";

const iranSans = localFont({
  src: "/fonts/Vazir-Bold.ttf",
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className={iranSans.variable}>
      <body className="font-iran-sans">
        <AuthProvider>
          <HeaderClient />
          <ConditionalLayout>{children}</ConditionalLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
